import type { TeamMember } from "../types";

export const teamMembers: TeamMember[] = [
  {
    id: "founder",
    name: "Muzammil Javed",
    role: "Founder & Head of AI Automation",
    bio: "As Founder, Muzammil established NexusGrowths with a vision to eliminate operational inefficiencies through intelligent automation. He designs and architects high-impact automation systems, ensuring long-term reliability, zero-maintenance infrastructure, and scalable growth for our partners.",
    image: "/team/muzammil-javed.png",
    imagePosition: "center 18%",
    imageScale: 1.12,
    linkedin: "https://www.linkedin.com/in/muzammil-javed-655297203/",
    badge: "Founder",
    tags: ["AI Automation", "n8n", "LLM Agents", "Full-Stack", "Systems Design", "Make", "OpenAI"],
    skillGroups: [
      { label: "AUTOMATION & AI", items: ["n8n", "LLM Agents", "Workflow Design", "OpenAI", "Make"] },
      { label: "ENGINEERING & SYSTEMS", items: ["Full-Stack", "Backend", "Infrastructure", "REST APIs", "Python"] },
    ],
    featured: true,
  },
  {
    id: "fullstack-ai",
    name: "Hasnain Ali",
    role: "Co-Founder & Full Stack Engineer",
    bio: "As the technical Co-Founder, Hasnain leads our engineering strategy and execution. He architects our custom web platforms, AI-powered backends, and robust n8n automation pipelines, transforming complex business bottlenecks into seamless, scalable digital infrastructures.",
    image: "/team/hasnain-ali.png",
    imagePosition: "center center",
    imageScale: 1.2,
    linkedin: "https://www.linkedin.com/in/hasnain-ali-fullstack-ai/",
    badge: "Technical Co-Founder",
    tags: [
      "Python",
      "FastAPI",
      "Django",
      "React",
      "Next.js",
      "React Native",
      "LangChain",
      "PyTorch",
    ],
    skillGroups: [
      {
        label: "Backend & AI",
        items: ["Python", "FastAPI", "Django", "LangChain", "RAG", "Pinecone", "PyTorch"],
      },
      {
        label: "Frontend & Mobile",
        items: ["React", "Next.js", "React Native", "Redux", "Zustand"],
      },
    ],
  },
  {
    id: "mobile-lead",
    name: "M. Salman",
    role: "Mobile Application Developer",
    bio: "Salman builds mobile apps that feel native and polished. 3+ years shipping Android apps to the Play Store, from first screen to final review.",
    image: "/team/m-salman.png",
    imagePosition: "center 12%",
    imageScale: 1.45,
    linkedin: "https://www.linkedin.com/in/muhammad-salman-5672a0203/",
    badge: "Mobile Lead",
    tags: [
      "Kotlin",
      "Flutter",
      "Jetpack Compose",
      "MVVM",
      "Firebase",
      "Supabase",
      "REST APIs",
      "Play Store",
    ],
    skillGroups: [
      {
        label: "Mobile",
        items: ["Native Android", "Flutter", "Jetpack Compose", "Material Design 3"],
      },
      {
        label: "Architecture",
        items: ["MVVM", "Clean Architecture", "Coroutines", "Hilt", "Room"],
      },
      {
        label: "Cloud & Release",
        items: ["Firebase", "Supabase", "FCM", "Retrofit", "Play Store"],
      },
    ],
  },
  {
    id: "wordpress-lead",
    name: "Rimsha Bajwa",
    role: "WordPress & WooCommerce Lead",
    bio: "Rimsha leads all WordPress development at NexusGrowths — from custom themes and plugins to WooCommerce stores and Elementor builds. She handles everything from local dev on LocalWP to live deployment on cPanel.",
    image: "/team/rimsha-bajwa.png",
    imagePosition: "center 15%",
    imageScale: 1.1,
    linkedin: "https://www.linkedin.com/in/rimsha-bajwa/",
    badge: "WordPress Lead",
    tags: [
      "WordPress",
      "WooCommerce",
      "Elementor",
      "PHP",
      "ACF",
      "REST API",
      "Custom Plugins",
      "SEO",
    ],
    skillGroups: [
      {
        label: "WordPress & CMS",
        items: ["Themes", "Plugins", "WooCommerce", "Elementor", "ACF", "CPT"],
      },
      {
        label: "Backend & Dev",
        items: ["PHP", "MySQL", "REST API", "AJAX", "Custom Hooks"],
      },
      {
        label: "DevOps & SEO",
        items: ["cPanel", "LocalWP", "Git", "SEO", "Security", "Performance"],
      },
    ],
  },
];
